# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1 # https://github.com/maxim-lobanov/setup-xcode
      with:
        xcode-version: '15.3'

    - name: Run tests
      run: | 
        xcodebuild clean test -project GitHubActionsTutorial.xcodeproj \
        -scheme GitHubActionsTutorial \
        -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'
